kind: pipeline
name: Change Hostname on Network Device
type: docker

steps:
  - name: Change Hostname to randi
    image: python:3.10  # This image comes with ssh command pre-installed
    environment:
      SSH_USER: "vikas"  # The SSH username
      SSH_PASS:
        from_secret: MY_PASS  # Retrieve SSH password from Drone secret
      DEVICE_IP: "192.168.1.14"  # The device IP address
    commands:
      # Use sshpass with the provided password to SSH into the device and change the hostname
      - echo "$SSH_PASS" | sshpass ssh -o StrictHostKeyChecking=no -o HostkeyAlgorithms=ssh-rsa $SSH_USER@$DEVICE_IP "conf t; hostname randi; end; write memory"

trigger:
  branch:
    include:
      - main
