kind: pipeline
name: default

steps:
  - name: change-hostname-and-bgp
    image: alpine:latest
    environment:
      DEVICE_IP: "192.168.1.6"
      SSH_USER: "tapesh"
      SSH_PASS: "tapesh"
    commands:
      - apk update
      - apk add --no-cache openssh sshpass
      # Force pseudo-terminal allocation (-t)
      - sshpass -p "$SSH_PASS" ssh -t -o StrictHostKeyChecking=no -o HostkeyAlgorithms=+ssh-rsa $SSH_USER@$DEVICE_IP <<EOF
          enable
          conf t
          hostname randi
          router bgp 65001
          bgp router-id 1.1.1.1
          network 192.168.1.0 mask 255.255.255.0
          end
          write memory
          exit
        EOF
