kind: pipeline
name: Change Hostname on Network Device

steps:
  - name: Change Hostname to randi
    image: alpine:latest  # Use the Alpine Linux image
    environment:
      SSH_USER: "vikas"        # SSH username
      DEVICE_IP: "192.168.1.14"  # IP address of the network device
      SSH_PASS: "tapesh"         # SSH password
    commands:
      - apk add --no-cache sshpass  # Install sshpass tool
      - echo "$SSH_PASS" | sshpass ssh -o StrictHostKeyChecking=no -o HostkeyAlgorithms=ssh-rsa $SSH_USER@$DEVICE_IP "conf t; hostname randi; end; write memory"  # Change hostname command

trigger:
  branch:
    include:
      - main
