kind: pipeline
name: Change Hostname on Network Device
type: docker

steps:
  - name: Change Hostname to randi
    image: alpine:latest  # Alpine image
    environment:
      SSH_USER: "vikas"
      DEVICE_IP: "192.168.1.14"
      SSH_PASS: "tapesh"
    commands:
      # Run the SSH command, will require manual password input
      - ssh -o StrictHostKeyChecking=no -o HostkeyAlgorithms=ssh-rsa $SSH_USER@$DEVICE_IP "conf t; hostname randi; end; write memory"

trigger:
  branch:
    include:
      - main
