kind: pipeline
type: docker
name: configure-cisco-router

steps:
  - name: configure-ios-xe
    image: alpine:latest
    environment:
      SSH_USER: tapesh
      SSH_PASS:
        from_secret: MY_PASS
      DEVICE_IP: 192.168.1.6
    commands:
      - apk add --no-cache openssh sshpass
      - |
        sshpass -p "$SSH_PASS" ssh -tt -o StrictHostKeyChecking=no -o HostkeyAlgorithms=+ssh-rsa $SSH_USER@$DEVICE_IP << EOF
        enable
        tapesh
        conf t
        hostname randi
        router bgp 65001
         bgp router-id 1.1.1.1
         network 192.168.1.0 mask 255.255.255.0
        end
        write memory
        exit
        EOF
