kind: pipeline
name: Change Hostname on Network Device
type: docker

steps:
  - name: Change Hostname to randi
    image: alpine:latest  # Using your existing base image
    environment:
      SSH_USER: "vikas"  # SSH username
      DEVICE_IP: "192.168.1.14"  # Device IP address
      SSH_PASS: "tapesh"  # The password for SSH authentication
    commands:
      # Install sshpass (needed for password-based SSH automation)
      - apk update
      - apk add --no-cache sshpass
      # Run SSH command to change hostname using password
      - echo "$SSH_PASS" | sshpass ssh -o StrictHostKeyChecking=no -o HostkeyAlgorithms=ssh-rsa $SSH_USER@$DEVICE_IP "conf t; hostname randi; end; write memory"

trigger:
  branch:
    include:
      - main
